# Production configuration for Clinical RAG system

# Pipeline settings
enable_cache: true

# Model settings
embedding_model: "all-MiniLM-L6-v2"
chunk_size: 800
chunk_overlap: 150

# Database settings
database:
  url: "${DATABASE_URL}"  # Use environment variable
  max_connections: 20
  
# Processing settings
processing:
  batch_size: 64
  save_temp_files: false
  temp_directory: "/tmp/clinical_rag"

# Search settings
search:
  default_similarity_threshold: 0.5
  default_top_k: 10
  enable_query_enhancement: true

# ZenML settings
settings:
  docker:
    requirements:
      - sentence-transformers==3.3.1
      - pdfplumber==0.10.3
      - psycopg2-binary==2.9.9
steps:
  extract_text_from_pdf:
    parameters:
      save_temp: false
  generate_embeddings:
    parameters:
      model_name: "all-MiniLM-L6-v2"